# WebSocket Signaling Service Configuration

# Service information
service:
  name: websocket-signaling
  version: 0.1.0
  description: "WebSocket Signaling Service for WebRTC streaming"
  environment: development

# HTTP server configuration
http:
  address: :8086
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

# WebSocket server configuration
websocket:
  address: :8087
  path: /ws
  read_timeout: 60s
  write_timeout: 10s
  ping_interval: 25s
  pong_timeout: 60s
  max_message_size: 1048576  # 1MB

# gRPC server configuration
grpc:
  address: :50052
  keep_alive_time: 60s
  keep_alive_timeout: 20s
  max_concurrent_streams: 100

# WebRTC out service
webrtc_out:
  address: webrtc-out:50053

# Stream router service
router:
  address: stream-router:9090

# Logging configuration
logging:
  level: info
  format: json
  output: stdout
