# WebSocket Signaling Service Configuration

# Service information
service:
  name: websocket-signaling
  version: 0.1.0
  description: "WebSocket Signaling Service for WebRTC streaming"
  environment: development

# HTTP server configuration
http:
  address: ":8086"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 15s

# WebSocket server configuration
websocket:
  address: ":8087"
  path: "/ws"
  read_timeout: 60s
  write_timeout: 10s

# gRPC server configuration
grpc:
  address: ":8088"
  keepalive_time: 30s
  keepalive_timeout: 10s
  max_concurrent_streams: 100

# WebRTC out service
webrtc_out:
  address: webrtc-out:50053

# Stream router service
router:
  address: stream-router:9090

# Logging configuration
log:
  level: "info"
  format: "text"
