version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"  # Exposing gRPC port
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./apps/api-gateway/config:/app/config
    depends_on:
      - stream-router
      - rtmp-ingestor
    networks:
      - streamhive-network

  stream-router:
    build:
      context: .
      dockerfile: apps/stream-router/Dockerfile
    ports:
      - "8082:8081"  # External:Internal - 8081 is what it's listening on internally
      - "9090:9090"  # gRPC port
    volumes:
      - ./apps/stream-router/config:/src/config
    environment:
      - HTTP_ADDRESS=:8081
      - GRPC_ADDRESS=:9090
    networks:
      - streamhive-network

  rtmp-ingestor:
    build:
      context: .
      dockerfile: apps/rtmp-ingestor/Dockerfile
    ports:
      - "8083:8081"  # HTTP port
      - "1935:1935"  # RTMP port
    volumes:
      - ./apps/rtmp-ingestor/config:/src/config
    environment:
      - HTTP_ADDRESS=:8081
      - RTMP_ADDRESS=:1935
      - ROUTER_ADDRESS=stream-router:9090
      - FRAME_SPLITTER_ADDRESS=frame-splitter:9091
    depends_on:
      - stream-router
      - frame-splitter
    networks:
      - streamhive-network

  frame-splitter:
    build:
      context: .
      dockerfile: apps/frame-splitter/Dockerfile
    ports:
      - "8084:8084"  # HTTP port
      - "9091:9091"  # gRPC port
    volumes:
      - ./apps/frame-splitter/config:/src/config
      - frame-data:/data/frames
    environment:
      - HTTP_ADDRESS=:8084
      - GRPC_ADDRESS=:9091
      - ROUTER_ADDRESS=stream-router:9090
    depends_on:
      - stream-router
    networks:
      - streamhive-network

  webrtc-out:
    build:
      context: .
      dockerfile: apps/webrtc-out/Dockerfile
    ports:
      - "8005:8005"  # HTTP port
    environment:
      - HTTP_ADDRESS=:8005
      - GRPC_ADDRESS=:9050
      - SIGNALING_SERVICE_ADDRESS=websocket-signaling:9002
      - REDIS_ADDRESS=redis:6379
      - NODE_ID=webrtc-out-1
      - ICE_SERVERS=[{"urls":["stun:stun.l.google.com:19302"]}]
    depends_on:
      - redis
      - websocket-signaling
    networks:
      - streamhive-network

  # WebSocket Signaling
  websocket-signaling:
    build:
      context: .
      dockerfile: apps/websocket-signaling/Dockerfile
    ports:
      - "8006:8006"  # WebSocket port
    environment:
      - HTTP_ADDRESS=:8006
      - GRPC_ADDRESS=:9002
      - REDIS_ADDRESS=redis:6379
      - NODE_ID=websocket-signaling-1
    depends_on:
      - redis
    networks:
      - streamhive-network

  # Redis (for service discovery, pub/sub, and caching)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - streamhive-network

networks:
  streamhive-network:
    driver: bridge

volumes:
  frame-data:
