version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "8080:8080"  # Keeping this the same
      - "50051:50051"  # Exposing gRPC port
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./apps/api-gateway/config:/app/config
    depends_on:
      - stream-router
      - rtmp-ingestor

  stream-router:
    build:
      context: .
      dockerfile: apps/stream-router/Dockerfile
    ports:
      - "8082:8081"  # External:Internal - 8081 is what it's listening on internally
      - "9090:9090"  # gRPC port
    volumes:
      - ./apps/stream-router/config:/src/config
    environment:
      - HTTP_ADDRESS=:8081
      - GRPC_ADDRESS=:9090

  rtmp-ingestor:
    build:
      context: .
      dockerfile: apps/rtmp-ingestor/Dockerfile
    ports:
      - "8083:8081"  # Changed to avoid clash with stream-router internal port
      - "1935:1935"  # RTMP port
    volumes:
      - ./apps/rtmp-ingestor/config:/src/config
    environment:
      - HTTP_ADDRESS=:8081
      - RTMP_ADDRESS=:1935
      - ROUTER_ADDRESS=stream-router:9090
    depends_on:
      - stream-router
