version: '3.8'

networks:
  streamhive-network:
    driver: bridge

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "8080:8080"  # HTTP API port
      - "50051:50051"  # gRPC port
      - "8082:8082"  # WebSocket port
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - GIN_MODE=release
    volumes:
      - ./apps/api-gateway/config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - stream-router
      - rtmp-ingestor
      - websocket-signaling
      - webrtc-out
    networks:
      - streamhive-network

  stream-router:
    build:
      context: .
      dockerfile: apps/stream-router/Dockerfile
    ports:
      - "8081:8081"  # HTTP port
      - "9090:9090"  # gRPC port
    volumes:
      - ./apps/stream-router/config:/app/config
    environment:
      - HTTP_ADDRESS=:8081
      - GRPC_ADDRESS=:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - streamhive-network

  rtmp-ingestor:
    build:
      context: .
      dockerfile: apps/rtmp-ingestor/Dockerfile
    ports:
      - "8083:8081"  # HTTP port
      - "1935:1935"  # RTMP port
    volumes:
      - ./apps/rtmp-ingestor/config:/app/config
    environment:
      - HTTP_ADDRESS=:8081
      - RTMP_ADDRESS=:1935
      - ROUTER_ADDRESS=stream-router:9090
      - FRAME_SPLITTER_ADDRESS=frame-splitter:9091
    depends_on:
      - stream-router
      - frame-splitter
    networks:
      - streamhive-network

  frame-splitter:
    build:
      context: .
      dockerfile: apps/frame-splitter/Dockerfile
    ports:
      - "8084:8084"  # HTTP port
      - "9091:9091"  # gRPC port
    volumes:
      - ./apps/frame-splitter/config:/app/config
      - frame-data:/data/frames
    environment:
      - HTTP_ADDRESS=:8084
      - GRPC_ADDRESS=:9091
      - ROUTER_ADDRESS=stream-router:9090
    depends_on:
      - stream-router
    networks:
      - streamhive-network

  # enhancement-service:
  #   build:
  #     context: .
  #     dockerfile: apps/enhancement-service/Dockerfile
  #   ports:
  #     - "8085:8085"  # HTTP port
  #     - "9092:9092"  # gRPC port
  #   volumes:
  #     - ./apps/enhancement-service/config:/app/config
  #   environment:
  #     - HTTP_ADDRESS=:8085
  #     - GRPC_ADDRESS=:9092
  #   depends_on:
  #     - stream-router
  #     - frame-splitter
  #   networks:
  #     - streamhive-network

  # encoder-service:
  #   build:
  #     context: .
  #     dockerfile: apps/encoder-service/Dockerfile
  #   ports:
  #     - "8089:8089"  # HTTP port
  #     - "9093:9093"  # gRPC port
  #   volumes:
  #     - ./apps/encoder-service/config:/app/config
  #   environment:
  #     - HTTP_ADDRESS=:8089
  #     - GRPC_ADDRESS=:9093
  #   depends_on:
  #     - stream-router
  #     - frame-splitter
  #   networks:
  #     - streamhive-network

  websocket-signaling:
    build:
      context: .
      dockerfile: apps/websocket-signaling/Dockerfile
    ports:
      - "8086:8086"  # HTTP port
      - "8087:8087"  # WebSocket port
      - "50052:50052"  # gRPC port
    volumes:
      - ./apps/websocket-signaling/config:/app/config
    environment:
      - HTTP_ADDRESS=:8086
      - WS_ADDRESS=:8087
      - GRPC_ADDRESS=:50052
      - WEBRTC_OUT_ADDRESS=webrtc-out:50053  # Use service name for DNS resolution
      - ROUTER_ADDRESS=stream-router:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - stream-router
      - webrtc-out
    networks:
      - streamhive-network

  webrtc-out:
    build:
      context: .
      dockerfile: apps/webrtc-out/Dockerfile
    ports:
      - "8088:8088"  # HTTP port
      - "50053:50053"  # gRPC port
    volumes:
      - ./apps/webrtc-out/config:/app/config
    environment:
      - HTTP_ADDRESS=:8088
      - GRPC_ADDRESS=:50053
      - FRAME_SPLITTER_ADDRESS=frame-splitter:9091
      - SIGNALING_ADDRESS=websocket-signaling:50052
      - ROUTER_ADDRESS=stream-router:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - frame-splitter
    networks:
      - streamhive-network

volumes:
  frame-data:
