# WebRTC Output Service Configuration

# Service information
service:
  name: webrtc-out
  version: 0.1.0
  description: "WebRTC Output Service for stream processing and delivery"
  environment: development

# HTTP server configuration
http:
  address: :8088
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

# gRPC server configuration
grpc:
  address: :50053
  keep_alive_time: 60s
  keep_alive_timeout: 20s
  max_concurrent_streams: 100

# WebRTC configuration
webrtc:
  ice_servers:
    - urls:
        - stun:stun.l.google.com:19302
        - stun:stun1.l.google.com:19302
  max_bitrate: 2000000  # 2 Mbps
  max_frame_rate: 30
  jitter_buffer: 50  # ms
  opus_min_bitrate: 6000  # 6 kbps
  opus_max_bitrate: 128000  # 128 kbps
  opus_complexity: 10
  max_stream_lifetime: 8h

# Stream Router service configuration
router:
  address: stream-router:9090

# Frame Splitter service configuration
frame_splitter:
  address: frame-splitter:9091

# WebSocket Signaling service configuration
signaling:
  address: websocket-signaling:50052

# Logging configuration
logging:
  level: info
  format: json
  output: stdout
