// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: libs/proto/webrtc/webrtc.proto

package webrtc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebRTCService_SendFrames_FullMethodName         = "/webrtc.WebRTCService/SendFrames"
	WebRTCService_GetWebRTCConfig_FullMethodName    = "/webrtc.WebRTCService/GetWebRTCConfig"
	WebRTCService_UpdateWebRTCConfig_FullMethodName = "/webrtc.WebRTCService/UpdateWebRTCConfig"
)

// WebRTCServiceClient is the client API for WebRTCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebRTCService handles WebRTC streaming
type WebRTCServiceClient interface {
	// Send frames to WebRTC
	SendFrames(ctx context.Context, in *SendFramesRequest, opts ...grpc.CallOption) (*SendFramesResponse, error)
	// Get the WebRTC configuration for a stream
	GetWebRTCConfig(ctx context.Context, in *GetWebRTCConfigRequest, opts ...grpc.CallOption) (*WebRTCConfig, error)
	// Update the WebRTC configuration for a stream
	UpdateWebRTCConfig(ctx context.Context, in *WebRTCConfig, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type webRTCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebRTCServiceClient(cc grpc.ClientConnInterface) WebRTCServiceClient {
	return &webRTCServiceClient{cc}
}

func (c *webRTCServiceClient) SendFrames(ctx context.Context, in *SendFramesRequest, opts ...grpc.CallOption) (*SendFramesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFramesResponse)
	err := c.cc.Invoke(ctx, WebRTCService_SendFrames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webRTCServiceClient) GetWebRTCConfig(ctx context.Context, in *GetWebRTCConfigRequest, opts ...grpc.CallOption) (*WebRTCConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebRTCConfig)
	err := c.cc.Invoke(ctx, WebRTCService_GetWebRTCConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webRTCServiceClient) UpdateWebRTCConfig(ctx context.Context, in *WebRTCConfig, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WebRTCService_UpdateWebRTCConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebRTCServiceServer is the server API for WebRTCService service.
// All implementations must embed UnimplementedWebRTCServiceServer
// for forward compatibility.
//
// WebRTCService handles WebRTC streaming
type WebRTCServiceServer interface {
	// Send frames to WebRTC
	SendFrames(context.Context, *SendFramesRequest) (*SendFramesResponse, error)
	// Get the WebRTC configuration for a stream
	GetWebRTCConfig(context.Context, *GetWebRTCConfigRequest) (*WebRTCConfig, error)
	// Update the WebRTC configuration for a stream
	UpdateWebRTCConfig(context.Context, *WebRTCConfig) (*emptypb.Empty, error)
	mustEmbedUnimplementedWebRTCServiceServer()
}

// UnimplementedWebRTCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebRTCServiceServer struct{}

func (UnimplementedWebRTCServiceServer) SendFrames(context.Context, *SendFramesRequest) (*SendFramesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFrames not implemented")
}
func (UnimplementedWebRTCServiceServer) GetWebRTCConfig(context.Context, *GetWebRTCConfigRequest) (*WebRTCConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebRTCConfig not implemented")
}
func (UnimplementedWebRTCServiceServer) UpdateWebRTCConfig(context.Context, *WebRTCConfig) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWebRTCConfig not implemented")
}
func (UnimplementedWebRTCServiceServer) mustEmbedUnimplementedWebRTCServiceServer() {}
func (UnimplementedWebRTCServiceServer) testEmbeddedByValue()                       {}

// UnsafeWebRTCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebRTCServiceServer will
// result in compilation errors.
type UnsafeWebRTCServiceServer interface {
	mustEmbedUnimplementedWebRTCServiceServer()
}

func RegisterWebRTCServiceServer(s grpc.ServiceRegistrar, srv WebRTCServiceServer) {
	// If the following call pancis, it indicates UnimplementedWebRTCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebRTCService_ServiceDesc, srv)
}

func _WebRTCService_SendFrames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFramesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRTCServiceServer).SendFrames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebRTCService_SendFrames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRTCServiceServer).SendFrames(ctx, req.(*SendFramesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebRTCService_GetWebRTCConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebRTCConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRTCServiceServer).GetWebRTCConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebRTCService_GetWebRTCConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRTCServiceServer).GetWebRTCConfig(ctx, req.(*GetWebRTCConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebRTCService_UpdateWebRTCConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebRTCConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRTCServiceServer).UpdateWebRTCConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebRTCService_UpdateWebRTCConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRTCServiceServer).UpdateWebRTCConfig(ctx, req.(*WebRTCConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// WebRTCService_ServiceDesc is the grpc.ServiceDesc for WebRTCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebRTCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webrtc.WebRTCService",
	HandlerType: (*WebRTCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFrames",
			Handler:    _WebRTCService_SendFrames_Handler,
		},
		{
			MethodName: "GetWebRTCConfig",
			Handler:    _WebRTCService_GetWebRTCConfig_Handler,
		},
		{
			MethodName: "UpdateWebRTCConfig",
			Handler:    _WebRTCService_UpdateWebRTCConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "libs/proto/webrtc/webrtc.proto",
}
