// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: libs/proto/signaling/signaling.proto

package signaling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_libs_proto_signaling_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_signaling_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignalRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_libs_proto_signaling_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_signaling_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_signaling_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_libs_proto_signaling_signaling_proto protoreflect.FileDescriptor

const file_libs_proto_signaling_signaling_proto_rawDesc = "" +
	"\n" +
	"$libs/proto/signaling/signaling.proto\x12\tsignaling\"H\n" +
	"\rSignalRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"(\n" +
	"\x0eSignalResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2U\n" +
	"\x10SignalingService\x12A\n" +
	"\n" +
	"SendSignal\x12\x18.signaling.SignalRequest\x1a\x19.signaling.SignalResponseB\x16Z\x14libs/proto/signalingb\x06proto3"

var (
	file_libs_proto_signaling_signaling_proto_rawDescOnce sync.Once
	file_libs_proto_signaling_signaling_proto_rawDescData []byte
)

func file_libs_proto_signaling_signaling_proto_rawDescGZIP() []byte {
	file_libs_proto_signaling_signaling_proto_rawDescOnce.Do(func() {
		file_libs_proto_signaling_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_proto_signaling_signaling_proto_rawDesc), len(file_libs_proto_signaling_signaling_proto_rawDesc)))
	})
	return file_libs_proto_signaling_signaling_proto_rawDescData
}

var file_libs_proto_signaling_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_libs_proto_signaling_signaling_proto_goTypes = []any{
	(*SignalRequest)(nil),  // 0: signaling.SignalRequest
	(*SignalResponse)(nil), // 1: signaling.SignalResponse
}
var file_libs_proto_signaling_signaling_proto_depIdxs = []int32{
	0, // 0: signaling.SignalingService.SendSignal:input_type -> signaling.SignalRequest
	1, // 1: signaling.SignalingService.SendSignal:output_type -> signaling.SignalResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libs_proto_signaling_signaling_proto_init() }
func file_libs_proto_signaling_signaling_proto_init() {
	if File_libs_proto_signaling_signaling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_proto_signaling_signaling_proto_rawDesc), len(file_libs_proto_signaling_signaling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_proto_signaling_signaling_proto_goTypes,
		DependencyIndexes: file_libs_proto_signaling_signaling_proto_depIdxs,
		MessageInfos:      file_libs_proto_signaling_signaling_proto_msgTypes,
	}.Build()
	File_libs_proto_signaling_signaling_proto = out.File
	file_libs_proto_signaling_signaling_proto_goTypes = nil
	file_libs_proto_signaling_signaling_proto_depIdxs = nil
}
