// libs/proto/frame/frame.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: libs/proto/frame/frame.proto

package frame

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FrameSplitterService_ProcessFrame_FullMethodName       = "/frame.FrameSplitterService/ProcessFrame"
	FrameSplitterService_ProcessFrameBatch_FullMethodName  = "/frame.FrameSplitterService/ProcessFrameBatch"
	FrameSplitterService_SubscribeToStream_FullMethodName  = "/frame.FrameSplitterService/SubscribeToStream"
	FrameSplitterService_RegisterConsumer_FullMethodName   = "/frame.FrameSplitterService/RegisterConsumer"
	FrameSplitterService_ListStreams_FullMethodName        = "/frame.FrameSplitterService/ListStreams"
	FrameSplitterService_RequestKeyFrame_FullMethodName    = "/frame.FrameSplitterService/RequestKeyFrame"
	FrameSplitterService_GetStreamConfig_FullMethodName    = "/frame.FrameSplitterService/GetStreamConfig"
	FrameSplitterService_UpdateStreamConfig_FullMethodName = "/frame.FrameSplitterService/UpdateStreamConfig"
	FrameSplitterService_GetStreamStats_FullMethodName     = "/frame.FrameSplitterService/GetStreamStats"
	FrameSplitterService_RestoreFrame_FullMethodName       = "/frame.FrameSplitterService/RestoreFrame"
)

// FrameSplitterServiceClient is the client API for FrameSplitterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FrameSplitterService handles frame processing and distribution
type FrameSplitterServiceClient interface {
	// ProcessFrame processes a single frame
	ProcessFrame(ctx context.Context, in *Frame, opts ...grpc.CallOption) (*ProcessFrameResponse, error)
	// ProcessFrameBatch processes a batch of frames
	ProcessFrameBatch(ctx context.Context, in *ProcessFrameBatchRequest, opts ...grpc.CallOption) (*ProcessFrameBatchResponse, error)
	// SubscribeToStream subscribes to a stream and receives frames
	SubscribeToStream(ctx context.Context, in *SubscribeToStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error)
	// RegisterConsumer registers a consumer service
	RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error)
	// ListStreams lists all active streams
	ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListStreamsResponse, error)
	// Request a key frame for a stream
	RequestKeyFrame(ctx context.Context, in *RequestKeyFrameRequest, opts ...grpc.CallOption) (*RequestKeyFrameResponse, error)
	// Get stream configuration
	GetStreamConfig(ctx context.Context, in *GetStreamConfigRequest, opts ...grpc.CallOption) (*StreamConfig, error)
	// Update stream configuration
	UpdateStreamConfig(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (*UpdateStreamConfigResponse, error)
	// Get stream statistics
	GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*StreamStats, error)
	// Restore a frame from backup
	RestoreFrame(ctx context.Context, in *RestoreFrameRequest, opts ...grpc.CallOption) (*Frame, error)
}

type frameSplitterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrameSplitterServiceClient(cc grpc.ClientConnInterface) FrameSplitterServiceClient {
	return &frameSplitterServiceClient{cc}
}

func (c *frameSplitterServiceClient) ProcessFrame(ctx context.Context, in *Frame, opts ...grpc.CallOption) (*ProcessFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessFrameResponse)
	err := c.cc.Invoke(ctx, FrameSplitterService_ProcessFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) ProcessFrameBatch(ctx context.Context, in *ProcessFrameBatchRequest, opts ...grpc.CallOption) (*ProcessFrameBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessFrameBatchResponse)
	err := c.cc.Invoke(ctx, FrameSplitterService_ProcessFrameBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) SubscribeToStream(ctx context.Context, in *SubscribeToStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FrameSplitterService_ServiceDesc.Streams[0], FrameSplitterService_SubscribeToStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToStreamRequest, Frame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrameSplitterService_SubscribeToStreamClient = grpc.ServerStreamingClient[Frame]

func (c *frameSplitterServiceClient) RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterConsumerResponse)
	err := c.cc.Invoke(ctx, FrameSplitterService_RegisterConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) ListStreams(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStreamsResponse)
	err := c.cc.Invoke(ctx, FrameSplitterService_ListStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) RequestKeyFrame(ctx context.Context, in *RequestKeyFrameRequest, opts ...grpc.CallOption) (*RequestKeyFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestKeyFrameResponse)
	err := c.cc.Invoke(ctx, FrameSplitterService_RequestKeyFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) GetStreamConfig(ctx context.Context, in *GetStreamConfigRequest, opts ...grpc.CallOption) (*StreamConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamConfig)
	err := c.cc.Invoke(ctx, FrameSplitterService_GetStreamConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) UpdateStreamConfig(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (*UpdateStreamConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStreamConfigResponse)
	err := c.cc.Invoke(ctx, FrameSplitterService_UpdateStreamConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*StreamStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamStats)
	err := c.cc.Invoke(ctx, FrameSplitterService_GetStreamStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameSplitterServiceClient) RestoreFrame(ctx context.Context, in *RestoreFrameRequest, opts ...grpc.CallOption) (*Frame, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Frame)
	err := c.cc.Invoke(ctx, FrameSplitterService_RestoreFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrameSplitterServiceServer is the server API for FrameSplitterService service.
// All implementations must embed UnimplementedFrameSplitterServiceServer
// for forward compatibility.
//
// FrameSplitterService handles frame processing and distribution
type FrameSplitterServiceServer interface {
	// ProcessFrame processes a single frame
	ProcessFrame(context.Context, *Frame) (*ProcessFrameResponse, error)
	// ProcessFrameBatch processes a batch of frames
	ProcessFrameBatch(context.Context, *ProcessFrameBatchRequest) (*ProcessFrameBatchResponse, error)
	// SubscribeToStream subscribes to a stream and receives frames
	SubscribeToStream(*SubscribeToStreamRequest, grpc.ServerStreamingServer[Frame]) error
	// RegisterConsumer registers a consumer service
	RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error)
	// ListStreams lists all active streams
	ListStreams(context.Context, *emptypb.Empty) (*ListStreamsResponse, error)
	// Request a key frame for a stream
	RequestKeyFrame(context.Context, *RequestKeyFrameRequest) (*RequestKeyFrameResponse, error)
	// Get stream configuration
	GetStreamConfig(context.Context, *GetStreamConfigRequest) (*StreamConfig, error)
	// Update stream configuration
	UpdateStreamConfig(context.Context, *StreamConfig) (*UpdateStreamConfigResponse, error)
	// Get stream statistics
	GetStreamStats(context.Context, *GetStreamStatsRequest) (*StreamStats, error)
	// Restore a frame from backup
	RestoreFrame(context.Context, *RestoreFrameRequest) (*Frame, error)
	mustEmbedUnimplementedFrameSplitterServiceServer()
}

// UnimplementedFrameSplitterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrameSplitterServiceServer struct{}

func (UnimplementedFrameSplitterServiceServer) ProcessFrame(context.Context, *Frame) (*ProcessFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessFrame not implemented")
}
func (UnimplementedFrameSplitterServiceServer) ProcessFrameBatch(context.Context, *ProcessFrameBatchRequest) (*ProcessFrameBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessFrameBatch not implemented")
}
func (UnimplementedFrameSplitterServiceServer) SubscribeToStream(*SubscribeToStreamRequest, grpc.ServerStreamingServer[Frame]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToStream not implemented")
}
func (UnimplementedFrameSplitterServiceServer) RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterConsumer not implemented")
}
func (UnimplementedFrameSplitterServiceServer) ListStreams(context.Context, *emptypb.Empty) (*ListStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedFrameSplitterServiceServer) RequestKeyFrame(context.Context, *RequestKeyFrameRequest) (*RequestKeyFrameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestKeyFrame not implemented")
}
func (UnimplementedFrameSplitterServiceServer) GetStreamConfig(context.Context, *GetStreamConfigRequest) (*StreamConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamConfig not implemented")
}
func (UnimplementedFrameSplitterServiceServer) UpdateStreamConfig(context.Context, *StreamConfig) (*UpdateStreamConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStreamConfig not implemented")
}
func (UnimplementedFrameSplitterServiceServer) GetStreamStats(context.Context, *GetStreamStatsRequest) (*StreamStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamStats not implemented")
}
func (UnimplementedFrameSplitterServiceServer) RestoreFrame(context.Context, *RestoreFrameRequest) (*Frame, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreFrame not implemented")
}
func (UnimplementedFrameSplitterServiceServer) mustEmbedUnimplementedFrameSplitterServiceServer() {}
func (UnimplementedFrameSplitterServiceServer) testEmbeddedByValue()                              {}

// UnsafeFrameSplitterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrameSplitterServiceServer will
// result in compilation errors.
type UnsafeFrameSplitterServiceServer interface {
	mustEmbedUnimplementedFrameSplitterServiceServer()
}

func RegisterFrameSplitterServiceServer(s grpc.ServiceRegistrar, srv FrameSplitterServiceServer) {
	// If the following call pancis, it indicates UnimplementedFrameSplitterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FrameSplitterService_ServiceDesc, srv)
}

func _FrameSplitterService_ProcessFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Frame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).ProcessFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_ProcessFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).ProcessFrame(ctx, req.(*Frame))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_ProcessFrameBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFrameBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).ProcessFrameBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_ProcessFrameBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).ProcessFrameBatch(ctx, req.(*ProcessFrameBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_SubscribeToStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrameSplitterServiceServer).SubscribeToStream(m, &grpc.GenericServerStream[SubscribeToStreamRequest, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrameSplitterService_SubscribeToStreamServer = grpc.ServerStreamingServer[Frame]

func _FrameSplitterService_RegisterConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).RegisterConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_RegisterConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).RegisterConsumer(ctx, req.(*RegisterConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_ListStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).ListStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_ListStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).ListStreams(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_RequestKeyFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestKeyFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).RequestKeyFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_RequestKeyFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).RequestKeyFrame(ctx, req.(*RequestKeyFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_GetStreamConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).GetStreamConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_GetStreamConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).GetStreamConfig(ctx, req.(*GetStreamConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_UpdateStreamConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).UpdateStreamConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_UpdateStreamConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).UpdateStreamConfig(ctx, req.(*StreamConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_GetStreamStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).GetStreamStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_GetStreamStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).GetStreamStats(ctx, req.(*GetStreamStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameSplitterService_RestoreFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameSplitterServiceServer).RestoreFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrameSplitterService_RestoreFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameSplitterServiceServer).RestoreFrame(ctx, req.(*RestoreFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FrameSplitterService_ServiceDesc is the grpc.ServiceDesc for FrameSplitterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrameSplitterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frame.FrameSplitterService",
	HandlerType: (*FrameSplitterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessFrame",
			Handler:    _FrameSplitterService_ProcessFrame_Handler,
		},
		{
			MethodName: "ProcessFrameBatch",
			Handler:    _FrameSplitterService_ProcessFrameBatch_Handler,
		},
		{
			MethodName: "RegisterConsumer",
			Handler:    _FrameSplitterService_RegisterConsumer_Handler,
		},
		{
			MethodName: "ListStreams",
			Handler:    _FrameSplitterService_ListStreams_Handler,
		},
		{
			MethodName: "RequestKeyFrame",
			Handler:    _FrameSplitterService_RequestKeyFrame_Handler,
		},
		{
			MethodName: "GetStreamConfig",
			Handler:    _FrameSplitterService_GetStreamConfig_Handler,
		},
		{
			MethodName: "UpdateStreamConfig",
			Handler:    _FrameSplitterService_UpdateStreamConfig_Handler,
		},
		{
			MethodName: "GetStreamStats",
			Handler:    _FrameSplitterService_GetStreamStats_Handler,
		},
		{
			MethodName: "RestoreFrame",
			Handler:    _FrameSplitterService_RestoreFrame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToStream",
			Handler:       _FrameSplitterService_SubscribeToStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "libs/proto/frame/frame.proto",
}
