// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: libs/proto/ingest/ingest.proto

package ingest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_libs_proto_ingest_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_ingest_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_ingest_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IngestRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_libs_proto_ingest_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_ingest_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_ingest_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_libs_proto_ingest_ingest_proto protoreflect.FileDescriptor

const file_libs_proto_ingest_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1elibs/proto/ingest/ingest.proto\x12\x06ingest\"@\n" +
	"\rIngestRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"(\n" +
	"\x0eIngestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2N\n" +
	"\rIngestService\x12=\n" +
	"\fIngestStream\x12\x15.ingest.IngestRequest\x1a\x16.ingest.IngestResponseB\x14Z\x12/libs/proto/ingestb\x06proto3"

var (
	file_libs_proto_ingest_ingest_proto_rawDescOnce sync.Once
	file_libs_proto_ingest_ingest_proto_rawDescData []byte
)

func file_libs_proto_ingest_ingest_proto_rawDescGZIP() []byte {
	file_libs_proto_ingest_ingest_proto_rawDescOnce.Do(func() {
		file_libs_proto_ingest_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_proto_ingest_ingest_proto_rawDesc), len(file_libs_proto_ingest_ingest_proto_rawDesc)))
	})
	return file_libs_proto_ingest_ingest_proto_rawDescData
}

var file_libs_proto_ingest_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_libs_proto_ingest_ingest_proto_goTypes = []any{
	(*IngestRequest)(nil),  // 0: ingest.IngestRequest
	(*IngestResponse)(nil), // 1: ingest.IngestResponse
}
var file_libs_proto_ingest_ingest_proto_depIdxs = []int32{
	0, // 0: ingest.IngestService.IngestStream:input_type -> ingest.IngestRequest
	1, // 1: ingest.IngestService.IngestStream:output_type -> ingest.IngestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libs_proto_ingest_ingest_proto_init() }
func file_libs_proto_ingest_ingest_proto_init() {
	if File_libs_proto_ingest_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_proto_ingest_ingest_proto_rawDesc), len(file_libs_proto_ingest_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_proto_ingest_ingest_proto_goTypes,
		DependencyIndexes: file_libs_proto_ingest_ingest_proto_depIdxs,
		MessageInfos:      file_libs_proto_ingest_ingest_proto_msgTypes,
	}.Build()
	File_libs_proto_ingest_ingest_proto = out.File
	file_libs_proto_ingest_ingest_proto_goTypes = nil
	file_libs_proto_ingest_ingest_proto_depIdxs = nil
}
